appDocentes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.login, name="login"),
    path('recup_pass/', views.recup_pass, name="recup_pass"),
    path('home/', views.home, name="home"),
    path('registro/', views.registro, name="registro"),
    path('editar/<str:clave_docente>/', views.edicion_docente, name='docente_edit')
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('appDocentes.urls') )
]

appDocentes/models.py
from django.db import models

class Docente(models.Model): # Tabla Docentes

    # DATOS PERSONALES ========================================================
    Nombre = models.CharField(max_length=100)
    ApellidoP = models.CharField(max_length=100)
    ApellidoM = models.CharField(max_length=100)
    FechaNacimiento = models.DateField()
    CedulaProfesional = models.CharField(max_length=50, unique=True, blank=True, null=True)
    GradoAcademico = models.CharField(max_length=50)
    EstadoCivil = models.CharField(max_length=30, choices=[('Casado', 'Casado'), ('Soltero', 'Soltero')])
    Sexo = models.CharField(max_length=10, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')])
    Residencia = models.CharField(max_length=100)
    Ciudad = models.CharField(max_length=100)
    Colonia = models.CharField(max_length=100)
    Discapacidad = models.CharField(max_length=50,null=True)


    # DATOS LABORALES =========================================================
    claveDocente = models.CharField(max_length=50, primary_key=True)
    Puesto = models.CharField(max_length=50)
    division = models.ForeignKey('Division', on_delete=models.PROTECT, null=True, blank=True)
    Perfil = models.CharField(max_length=50, choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Por Asignatura', 'Por Asignatura')]) # Ejemplo: 'Tiempo Completo', 'Medio Tiempo'
    FechaIngreso = models.DateField()
    OtroEmpleo = models.CharField(max_length=2, choices=[('Si', 'Si'), ('No', 'No')], default='No')
    categoria = models.CharField(max_length=10, null=True)
    base = models.CharField(max_length=20, null=True)
    status = models.CharField(max_length=20, null=True)
    tutorado = models.CharField(max_length=2, choices=[('Si', 'Si'), ('No', 'No')], default='No', null=True)
    programaE = models.ForeignKey('ProgramaEducativo', on_delete=models.PROTECT, null=True, blank=True)
    areaC = models.ForeignKey('AreaConocimiento', on_delete=models.PROTECT, null=True, blank=True)
    fechaInactividad = models.DateField(null=True,blank=True)
    tipoInactividad = models.CharField(null=True,blank=True)


    # DATOS DE CONTACTO =======================================================
    correoInstitucional = models.EmailField(max_length=100, unique=True)
    correoPersonal = models.EmailField(max_length=100, blank=True, null=True)
    Telefono = models.CharField(max_length=20, blank=True, null=True)
    cuentaTeams = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.claveDocente} - {self.Nombre} {self.ApellidoP}"
    
class Division(models.Model): #Tabla Division
    claveDivision = models.CharField(max_length=10, primary_key=True)
    Nombre = models.CharField(max_length=100,null=True)
    Calle = models.CharField(max_length=100,null=True)
    Col = models.CharField(max_length=100,null=True)
    Ciudad = models.CharField(max_length=100,null=True)
    NumExt = models.CharField(max_length=10,null=True)
    CodigoP = models.CharField(max_length=10,null=True)

    def __str__(self):
        return self.claveDivision
    
class ProgramaEducativo(models.Model):
    idPe = models.CharField(max_length=10, primary_key=True)
    Nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.idPe
    
class AreaConocimiento(models.Model):
    IdAreaC = models.CharField(max_length=10, primary_key=True)
    Nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.Nombre

class Asignatura(models.Model):
    clave_asignatura = models.CharField(max_length=20, primary_key=True)
    nombre = models.CharField(max_length=100)
    id_area = models.ForeignKey('AreaConocimiento', on_delete=models.CASCADE)
    id_division = models.ForeignKey('Division', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

class SEI(models.Model):
    id_sei = models.IntegerField(primary_key=True)
    superfave = models.CharField(max_length=50)
    nivel = models.CharField(max_length=50)
    clave_docente = models.ForeignKey('Docente', on_delete=models.CASCADE)
    def __str__(self):
        return f"SEI de {self.clave_docente}"

class Promep(models.Model):
    id_promep = models.IntegerField(primary_key=True)
    superfave = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    clave_docente = models.ForeignKey('Docente', on_delete=models.CASCADE)

    def __str__(self):
        return f"Promep de {self.clave_docente}"

class ProyectoInvestigacion(models.Model):
    id_proyecto = models.CharField(max_length=20, primary_key=True)
    superllave = models.CharField(max_length=50)
    nombre = models.CharField(max_length=200)
    colaboradores=models.CharField(max_length=200,null=True,blank=True)
    descripcion=models.CharField(max_length=500,null=True,blank=True)
    clave_docente = models.ForeignKey('Docente', on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class CedulaLicenciatura(models.Model):
    num_ced_lic = models.CharField(max_length=20, primary_key=True)
    nombre = models.CharField(max_length=100)
    institucion = models.CharField(max_length=100)
    fecha_obtencion = models.DateField()
    clave_docente = models.ForeignKey('Docente', on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Cédula Lic. de {self.clave_docente}"

class CedulaMaestria(models.Model):
    num_ced_m = models.CharField(max_length=20, primary_key=True)
    nombre = models.CharField(max_length=100)
    institucion = models.CharField(max_length=100)
    fecha_obtencion = models.DateField()
    clave_docente = models.ForeignKey('Docente', on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Cédula Maestría de {self.clave_docente}"

class CedulaDoctorado(models.Model):
    num_ced_dr = models.CharField(max_length=20, primary_key=True)
    nombre = models.CharField(max_length=100)
    institucion = models.CharField(max_length=100)
    fecha_obtencion = models.DateField()
    clave_docente = models.ForeignKey('Docente', on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Cédula Doctorado de {self.clave_docente}"

appDocentes/forms.py
from django import forms
from .models import Docente, Division

class DocenteForm(forms.ModelForm):
    class Meta:
        model = Docente
        fields = '__all__'
        
        labels = {
            # Personales
            'Nombre': 'Nombre',
            'ApellidoP': 'Apellido Paterno',
            'ApellidoM': 'Apellido Materno',
            'FechaNacimiento': 'Fecha de Nacimiento',
            'CedulaProfesional': 'Cédula Profesional',
            'GradoAcademico': 'Grado Académico',
            'EstadoCivil': 'Estado Civil',
            'Sexo': 'Sexo',
            'Residencia': 'Residencia',
            'Ciudad': 'Ciudad',
            'Colonia': 'Colonia',
            'Discapacidad' : 'Discapacidad',
            # Laborales
            'claveDocente': 'Matrícula',
            'Puesto': 'Puesto',
            'division': 'División',
            'Perfil': 'Perfil',
            'FechaIngreso': 'Fecha de Ingreso',
            'OtroEmpleo': 'Otro Empleo',
            'categoria': 'Categoría',
            'base': 'Base',
            'status': 'Status',
            'tutorado': 'Tutorado',
            'programaE': 'Programa Educativo',
            'areaC': 'Área de Conocimiento',
            # Contacto
            'correoInstitucional': 'Correo Institucional',
            'correoPersonal': 'Correo Personal',
            'Telefono': 'Teléfono',
            'cuentaTeams': 'Cuenta Teams'
        }


class DocenteEdit(forms.ModelForm):
    # Opcional pero recomendado: Desactivar la edición de la clave primaria (Matrícula)
    # Esto evita que el usuario cambie la llave, lo cual puede causar errores de base de datos.
    claveDocente = forms.CharField(label='Matrícula', max_length=50, disabled=True) 

    class Meta:
        model = Docente
        fields = '__all__'
        
        # Copia de los labels para mantener consistencia
        labels = {
            # Personales
            'Nombre': 'Nombre',
            'ApellidoP': 'Apellido Paterno',
            'ApellidoM': 'Apellido Materno',
            'FechaNacimiento': 'Fecha de Nacimiento',
            'CedulaProfesional': 'Cédula Profesional',
            'GradoAcademico': 'Grado Académico',
            'EstadoCivil': 'Estado Civil',
            'Sexo': 'Sexo',
            'Residencia': 'Residencia',
            'Ciudad': 'Ciudad',
            'Colonia': 'Colonia',
            'Discapacidad' : 'Discapacidad',
            # Laborales
            'claveDocente': 'Matrícula',
            'Puesto': 'Puesto',
            'division': 'División',
            'Perfil': 'Perfil',
            'FechaIngreso': 'Fecha de Ingreso',
            'OtroEmpleo': 'Otro Empleo',
            'categoria': 'Categoría',
            'base': 'Base',
            'status': 'Status',
            'tutorado': 'Tutorado',
            'programaE': 'Programa Educativo',
            'areaC': 'Área de Conocimiento',
            # Contacto
            'correoInstitucional': 'Correo Institucional',
            'correoPersonal': 'Correo Personal',
            'Telefono': 'Teléfono',
            'cuentaTeams': 'Cuenta Teams'
        }
        
        # Mantenemos los widgets para los campos de fecha
        widgets = {
            'FechaNacimiento': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date'}),
            'FechaIngreso': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date'}),
        }

appDocentes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .forms import DocenteForm, DocenteEdit 
from django.shortcuts import render, get_object_or_404
from .models import Docente, Division, ProgramaEducativo, AreaConocimiento
from datetime import date
 

def login(request):
    if request.method == 'POST':
        return redirect('home')
    return render(request, 'login.html')

def recup_pass(request):
    return render(request, 'recup_pass.html')

# app/views.py

def home(request):
    hoy = date.today()

    #filtros
    filtros = {}
    puesto_seleccionado = request.GET.get('puesto', '')
    perfil_seleccionado = request.GET.get('perfil', '')

    if puesto_seleccionado:
        filtros['Puesto'] = puesto_seleccionado
    
    if perfil_seleccionado:
        filtros['Perfil'] = perfil_seleccionado 

    docentes_qs = Docente.objects.filter(**filtros).select_related('division').order_by('ApellidoP')
    
    # Antiguedad
    docentes_con_antiguedad = []
    for docente in docentes_qs:
        antiguedad_anios = hoy.year - docente.FechaIngreso.year
        if (hoy.month, hoy.day) < (docente.FechaIngreso.month, docente.FechaIngreso.day):
            antiguedad_anios -= 1
        docente.antiguedad = antiguedad_anios
        docentes_con_antiguedad.append(docente)
        
    opciones_puesto = Docente.objects.values_list('Puesto', flat=True).distinct()
    opciones_perfil = Docente.Perfil.field.choices 
    
    context = {
        'docentes': docentes_con_antiguedad,
        'opciones_puesto': opciones_puesto,
        'opciones_perfil': opciones_perfil,
        

        'puesto_seleccionado': puesto_seleccionado,
        'perfil_seleccionado': perfil_seleccionado,
    }
    
    return render(request, 'home.html', context)

def registro(request):
    if request.method == 'POST':
        form = DocenteForm(request.POST)
        if form.is_valid():
            docente_guardado = form.save()
            return redirect('home') # Debes definir esta URL
        else:
            print(form.errors) # Muestra los errores en la consola del servidor
            
    else:
        form = DocenteForm()
    contexto = {
        'form': form
    }
    return render(request, 'registro.html', contexto)

def edicion_docente(request, clave_docente):
    # 1. Obtener el objeto Docente o devolver un 404 si no existe
    docente = get_object_or_404(Docente, claveDocente=clave_docente)

    if request.method == 'POST':
        # Cuando se envía el formulario:
        # Instanciar el formulario con los datos POST y la instancia del docente existente
        form = DocenteForm(request.POST, instance=docente)
        
        if form.is_valid():
            # El form.save() actualiza la instancia existente
            form.save()
            # Redirigir a la vista principal después de guardar
            return redirect('home')  
    else:
        # Cuando se carga la página (GET):
        # Instanciar el formulario con los datos del docente existente
        form = DocenteForm(instance=docente)

    context = {
        'form': form,
        'docente': docente,
    }
    return render(request, 'edicion_docente.html', context)
 

appDocentes/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Tu Aplicación{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'Styles/base.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>

<body>
    <div id="menu-overlay" onclick="closeNav()"></div>
    
    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        
        <a href="{% url 'home' %}">Inicio</a>
        <a href="{% url 'registro' %}" class="{% if request.path == '/registro/' %}active{% endif %}">Registro de Docentes</a>
        <a href="#">Reportes</a>
        <a href="#">Configuración</a>
    </div>

    <div id="main">
        
        <header>
            <button class="openbtn" onclick="openNav()">☰ Gesto-UJAT</button>
        </header>

        <div class="content-wrapper">
            {% block content %}
            {% endblock %}
        </div>

    </div> <script>
        function openNav() {
            document.getElementById("mySidebar").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
            document.getElementById("menu-overlay").style.display = "block";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            document.getElementById("menu-overlay").style.display = "none";
        }
    </script>
</body>
</html>

appDocentes/templates/edicion_docente.html
{% extends "base.html" %}
{% load static %}

{% block title %}Editar Docente | {{ docente.Nombre }} {{ docente.ApellidoP }}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'Styles/registro.css' %}">
{% endblock %}


{% block content %}

    <div class="page-container">
        <header class="form-header">
            <a href="{% url 'home' %}" class="back-link">&larr; Regresar</a>
        </header>

        <form method="post" class="data-form">
            {% csrf_token %}
            
            <section class="form-section">
                <h2>Datos Personales</h2>
                <div class="form-grid">
                    {% for field in form %}
                        {% if field.name in 'Nombre,ApellidoP,ApellidoM,FechaNacimiento,CedulaProfesional,GradoAcademico,EstadoCivil,Sexo,Residencia,Ciudad,Colonia,Discapacidad' %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.errors %}
                                    <small style="color: red;">{{ field.errors }}</small>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </section>
            
            <section class="form-section">
                <h2>Datos Laborales</h2>
                <div class="form-grid">
                     {% for field in form %}
                        {% if field.name in 'claveDocente,Puesto,division,Perfil,FechaIngreso,OtroEmpleo,categoria,base,status,tutorado,programaE,areaC' %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.errors %}
                                    <small style="color: red;">{{ field.errors }}</small>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </section>

            <section class="form-section">
                <h2>Datos de Contacto</h2>
                <div class="form-grid">
                     {% for field in form %}
                        {% if field.name in 'correoInstitucional,correoPersonal,Telefono,cuentaTeams' %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.errors %}
                                    <small style="color: red;">{{ field.errors }}</small>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </section>


            <div class="form-actions">
                <button type="submit" class="save-button">Guardar Cambios</button>
            </div>
        </form>
    </div>
    
{% endblock content %}

appDocentes/templates/home.html
{% extends "base.html" %} 

{% block title %}Docentes | Vista Principal{% endblock %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'Styles/home.css' %}">
</head>

<body>
    
    <section class="page-header">
        <div class="page-titles">
            <h1>Bienvenido</h1>
            <h2>Aquí puedes gestionar todos los datos de forma sencilla</h2>
        </div>
        <div>
            <a href="{% url 'registro' %}" class="add-professor-button">
                Agregar Profesor
            </a>
        </div>
    </section>

    <section class="filter-section">
        <form method="GET" action="{% url 'home' %}" class="filter-form">
            <label for="puesto">Puesto:</label>
            <select name="puesto" id="puesto">
                <option value="">-- Todos los Puestos --</option>
                {% for puesto in opciones_puesto %}
                    <option value="{{ puesto }}" {% if puesto == puesto_seleccionado %}selected{% endif %}>
                        {{ puesto }}
                    </option>
                {% endfor %}
            </select>

            <label for="perfil">Perfil:</label>
            <select name="perfil" id="perfil">
                <option value="">-- Todos los Perfiles --</option>
                {% for clave, etiqueta in opciones_perfil %}
                    <option value="{{ clave }}" {% if clave == perfil_seleccionado %} selected{% endif %}>
                        {{ etiqueta }}
                    </option>
                {% endfor %}
            </select>

            <button type="submit" class="btn-filter">Aplicar Filtros</button>
            
            <a href="{% url 'home' %}" class="btn-clear-filter">Limpiar Filtros</a>
        </form>
    </section>

    <section>
        <div class="table-container">
            
            <div class="fixed-column-wrapper">
                <table class="fixed-table">
                    <thead>
                        <tr>
                            <th>Clave docente</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for docente in docentes %}
                        <tr>
                            <td>
                                <a href="{% url 'docente_edit' clave_docente=docente.claveDocente %}" class="edit-link">
                                    {{ docente.claveDocente }}
                                </a>
                                
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="scrollable-content-wrapper">
                <table class="scrollable-table">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido paterno</th>
                            <th>Apellido materno</th>
                            <th>Puesto</th>
                            <th>Base</th>
                            <th>Perfil</th>
                            <th>Fecha de ingreso</th>
                            <th>Antigüedad</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for docente in docentes %}
                        <tr>
                            <td>{{ docente.Nombre }}</td>
                            <td>{{ docente.ApellidoP }}</td>
                            <td>{{ docente.ApellidoM }}</td>
                            <td>{{ docente.Puesto }}</td> 
                            <td>{{ docente.base }}</td>
                            <td>{{ docente.get_Perfil_display }}</td> 
                            <td>{{ docente.FechaIngreso|date:"Y-m-d"}}</td>
                            <td>{{ docente.antiguedad }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="8" style="text-align: center;">No hay docentes registrados todavía.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</body>
</html>

{% endblock %}

appDocentes/templates/login.html
{% load static  %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de sesión</title>
    
    <link rel="stylesheet" href="{% static 'Styles/login.css' %}">

</head>
<body>  
    <div class="container">
        <div class="image-section">
            <img src="{% static 'img_login.jpg' %}" alt="Edificio">
        </div>
        <div class="login-section">
            <div class="login-box">
                <h1 class="welcome-title">¡Le damos la bienvenida!</h1>
                <p class="login-instruction">Inicie sesión en su cuenta</p>
                <form action="#" method="post" class="login-form">
                    <label for="email" class="form-label">Correo electrónico</label>
                    <input type="email" id="email" name="email" class="form-input" required>
                    
                    <label for="password" class="form-label">Contraseña</label>
                    <input type="password" id="password" name="password" class="form-input" required>
                    <a href="{% url 'recup_pass' %}" class="forgot-password">¿Olvidó su contraseña?</a>
                </form>

                <form action="{% url 'home' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="login-button">Iniciar sesión</button>
                </form>                
                
                <div class="no-account-box">
                    <h2 class="no-account-title">¿No tienes una cuenta?</h2>
                    <p class="no-account-text">
                        En caso de no tener una cuenta debe ponerse en contacto con el administrador general del sistema.
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

appDocentes/templates/recup_pass.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recuperar Contraseña</title>
    <link rel="stylesheet" href="{% static 'Styles/login.css' %}"> 
</head>
<body>
    <div class="container">
        
        <div class="image-section">
            <img src="{% static 'img_login.jpg' %}" alt="Edificio institucional">
        </div>

        <div class="login-section">
            <div class="login-box">
                
                <a href="{% url 'login' %}" class="back-link-form">&larr; Regresar</a>
                
                <h2 class="welcome-title">Recuperar Contraseña</h2>
                <p class="login-instruction">
                    Ingresa tu dirección de correo electrónico. Te enviaremos un mensaje para restablecerla.
                </p>

                <form method="post" action="#" class="login-form">
                    {% csrf_token %}

                    <label for="email" class="form-label">Correo electrónico</label>
                    <input type="email" id="email" name="email" class="form-input" required>

                    <button type="submit" class="login-button">Enviar</button>
                </form>
                
                </div>
        </div>
    </div>
</body>
</html>